apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.agentServiceName }}
  namespace: km-agent
  labels:
    {{- toYaml .Values.serviceLabels | nindent 4 }}
spec:
  selector:
    mapped-with: {{ .Values.daemonsetName }}
  ports:
    - name: otlp-grpc-service
      protocol: TCP
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http-service
      protocol: TCP
      port: 4318
      targetPort: otlp-http
    - name: health-check
      port: 13133
      targetPort: 13133
      protocol: TCP
  type: ClusterIP
  internalTrafficPolicy: Local