apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRoleName }}
  namespace: km-agent
  labels:
    {{- toYaml .Values.clusterRoleLabels | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      [
        "nodes",
        "pods",
        "services",
        "endpoints",
        "namespaces",
        "configmaps",
        "secrets",
        "events",
        "persistentvolumes",
        "replicationcontrollers",
        "resourcequotas",
        "nodes/stats",
        "nodes/proxy",
      ]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "update"]

  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["list", "watch"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["list", "watch"]

  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
