apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.configUpdaterName }}
  namespace: km-agent
  labels:
    {{- toYaml .Values.configUpdaterLabels | nindent 4 }}
spec:
  # replica is 1 to ensure a single instance is running
  replicas: 1
  selector:
    matchLabels:
      {{- toYaml .Values.configUpdaterLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.configUpdaterLabels | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: config-updater
          image: "{{ .Values.configUpdater.image.repository }}:{{ .Values.configUpdater.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.configUpdater.image.pullPolicy }}
          env:
            - name: KM_API_KEY
              value: {{ .Values.API_KEY }}
            - name: KM_COLLECTOR_ENDPOINT
              value: {{ .Values.COLLECTOR_ENDPOINT | default "https://otel.kloudmate.com:4318" }}
            - name: KM_CONFIG_CHECK_INTERVAL
              value: {{ .Values.KM_CONFIG_CHECK_INTERVAL | default "30s" }}
            - name: KM_UPDATE_ENDPOINT
              value: {{ .Values.KM_UPDATE_ENDPOINT | default "https://api.kloudmate.com/agents/config-check" }}
              ## for daemonset
            - name: CONFIGMAP_DAEMONSET_NAME
              value: {{ .Values.configMapDaemonsetName }}
              ## for deployment
            - name: CONFIGMAP_DEPLOYMENT_NAME
              value: {{ .Values.configMapDeploymentName }}
            - name: KM_CLUSTER_NAME
              value: {{ .Values.clusterName }}
            - name: KM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KM_DAEMONSET_NAME
              value: {{ .Values.daemonsetName }}
            - name: KM_DEPLOYMENT_NAME
              value: {{ .Values.deploymentName }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"